config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  resources :surveys
  resources :responses
  resources :responses
  resources :questions
  root to: 'surveys#home'
  get 'dashboard' => 'students#dashboard'
  get 'improving_human_values' => 'students#improving_human_values'
  get 'new_student' => 'students#new'
  get 'student_list' => 'students#index'
  post 'create_student' => 'students#create'

end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/students/confirmations_controller.rb
class Students::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/students/omniauth_callbacks_controller.rb
class Students::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/students/passwords_controller.rb
class Students::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/students/registrations_controller.rb
class Students::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students/sessions_controller.rb
class Students::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/students/unlocks_controller.rb
class Students::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :student_is_admin, only: [:create, :index, :new]
  before_action :authenticate_student!

  def dashboard
    @surveys = Survey.all
  end

  def improving_human_values
  end

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to student_list_path, notice: "Student was successfully created."
    else
      redirect_to student_list_path, notice: "Student was not created."
    end
  end

  private

  def student_params
    params.require(:student).permit(
      :email,
      :password
    )
  end

  def student_is_admin
    if current_student.admin?
    else
      redirect_to :back, notice: "Unauthorized access"
    end
  end
end

app/views/students/_form.html.erb
<br>
<div class="container">
  <div class=“row”>
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-primary">
        <div class="panel-body">
          <%= simple_form_for @student, :url => create_student_path, :method => :post, html: { multipart: true } do |f| %>
            <%= f.input :email, label:"students email"%>
            <%= f.input :password %>
            <%= f.input :password_confirmation %>
            <%= f.button :submit, "Create Student", class: "btn btn-default" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/dashboard.html.erb
<center>
  <div class="container-survey">
    <h2>Survey</h2>
    <p>Please choose a survey</p>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= link_to "Imporving Human Values", improving_human_values_path %></td>
        </tr>
      </tbody>
    </table>
  </div>
</center>

app/views/students/improving_human_values.html.erb
<br>
<center>
<script>(function(t,e,o,n){var s,c,i;t.SMCX=t.SMCX||[],e.getElementById(n)||(s=e.getElementsByTagName(o),c=s[s.length-1],i=e.createElement(o),i.type="text/javascript",i.async=!0,i.id=n,i.src=["https:"===location.protocol?"https://":"http://","widget.surveymonkey.com/collect/website/js/nZ7i1JEU0Uz72M1hkQPzQz4Mit89eF5umOLQKEfM38jHjKeEpmx29Ctoyh1lXUop.js"].join(""),c.parentNode.insertBefore(i,c))})(window,document,"script","smcx-sdk");</script><a style="font: 12px Helvetica, sans-serif; color: #999; text-decoration: none;" href=https://www.surveymonkey.com/mp/customer-satisfaction-surveys/> Create your own user feedback survey </a>
</center>

app/views/students/index.html.erb
<br>
<div class="container">
  <div class=“row”>
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-primary">
        <div class="panel-body">
          <ul class="students">
            <button type="button" class="btn btn-default btn-lg">
              <%= link_to "add new student", new_student_path %>
            </button>
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>email</th>
                </tr>
              </thead>
              <tbody>
                <% @students.each do |s| %>
                  <tr>
                    <td>
                      <%= s.email %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/new.html.erb
<center><h1>Create New Student</h1></center>
<%= render 'form' %>