config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  resources :surveys
  resources :responses
  resources :responses
  resources :questions
  root to: 'surveys#home'
  get 'dashboard' => 'students#dashboard'
  get 'improving_human_values' => 'students#improving_human_values'
  get 'new_student' => 'students#new'
  get 'student_list' => 'students#index'
  post 'create_student' => 'students#create'

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :questions
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  def home

  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
    14.times do
      @survey.questions.build
    end
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:title)
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/home.html.erb
    <section id="main-slider">
        <div class="owl-carousel">
            <div class="item" style="background-image: url(http://s18.postimg.org/r95zesa61/mountain_lake_984482_1920.jpg);">
                <div class="slider-inner">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="carousel-content">
                                    <div class = "slider_title">What do we do?</div>
                                    <div class = "slider_caption">A unique and powerful not-for-profit training program designed to release the potential within everybody.</div>
                                    <button type="button" class="btn btn-default btn-lg">
                                        <%= link_to "Get started", new_student_registration_path %>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.item-->
        </div><!--/.owl-carousel-->
    </section><!--/#main-slider-->

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

  <a  name="services"></a>

    <!-- /.content-section-a -->
    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">What do we do?</h2>
                    <p class="lead">We go beyond rules and lectures to create a safe and self challenging process with amazing outcomes.</p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <div class="img-responsive hero-image">
                      <%=image_tag("hero-img-2.jpg")%>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->
    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">We are here to help you.</h2>
                    <p class="lead">Let’s get started!</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <div class="img-responsive hero-image">
                      <%=image_tag("hero-img-3.jpg")%>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

  <a  name="contact"></a>
    <div class="banner">

        <div class="container">



        </div>
        <!-- /.container -->

    </div>
    <!-- /.banner -->

app/views/surveys/index.html.erb
<h1>Listing Surveys</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.title %></td>
        <td><%= link_to 'Show', survey %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <div class"survey_title"><%= @survey.title %></div>
  <div class"survey_question"><% @survey.questions.each do |q| %></div>
    <li>
      <li class"question_title"><%= q.title %></li>
    </li>
    <% q.responses.each do |response| %>
      <li class"reponse_title"><%= response.title %></li>
    <% end %>
  <% end %>
</p>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>