config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  resources :surveys
  resources :responses
  resources :responses
  resources :questions
  root to: 'surveys#home'
  get 'dashboard' => 'students#dashboard'
  get 'improving_human_values' => 'students#improving_human_values'
  get 'new_student' => 'students#new'
  get 'student_list' => 'students#index'
  post 'create_student' => 'students#create'

end

app/views/layouts/_footer.html.erb
<footer class="footer">

    <!--/.footer-->
    <div class="footer-bottom">
        <div class="container">
            <ul>
                <a href="http://vitalprojex.com/">
                    <li><%=image_tag("WEBSITE-ICON.png")%></li>
                </a>
                <a href="http://vimeo.com/user5104885">
                    <li><%=image_tag("VIMEO-ICON.png")%></li>
                </a>
            </ul>

            <p>
                Character Snapshot
            </p>
            <p id="sub-text">
                &copy; 2015 Vital Projects Australia Trust - All rights reserved.
            </p>
        </div>
    </div>
    <!--/.footer-bottom-->
</footer>

app/views/layouts/_header.html.erb
    <header id="header">
        <nav id="main-menu" class="navbar navbar-default navbar-fixed-top" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/"><%=image_tag("VITAL-Logo.png")%></a>
                </div>

                <div class="collapse navbar-collapse navbar-right">
                    <ul class="nav navbar-nav">
                      <% if student_signed_in? %>
                        <li><%= link_to "Students", student_list_path %></li>
                        <li><%= link_to "Dashboard", dashboard_path %></li>
                        <li><%= link_to "Sign Out", destroy_student_session_path, :method => :delete %></li>
                      <% else %>
                        <li><%= link_to "Log In", new_student_session_path %></li>
                        <li><%= link_to "Sign Up", new_student_registration_path %></li>
                      <% end %>
                    </ul>
                </div>
            </div><!--/.container-->
        </nav><!--/nav-->
    </header><!--/header-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VitalProjects</title>
  <%= javascript_include_tag :defaults, "nested_form" %>
  <%= stylesheet_link_tag    'custom' %>
  <%= stylesheet_link_tag    'extra' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>

<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>